query GetWorkspaceInfo($userId: String!){
    user(userId: $userId){
        username
        status
        role
        hostChannels {
            uid
            name
            isDefaultChannel
        }
        followChannels{
            uid
            channelId
        }
    }
}
